export const ERROR_CODE_TYPES = {
  PASSWORD_ACCOUNT_LOCKED: "17",
  INVALID_CREDENTIALS: "07",
  GENERAL_ERROR: "06",
  PIN_MISMATCH: "77",
  TEMPORAL_PASSWORD_USED: "18",
  DEVICE_NOT_LINKED: "16",
  PIN_ACCOUNT_LOCKED: "14",
  INELIGIBLE: "90",
  BAD_CREDIT: "80",
  CIF_CREATED: "27",
  CUSTOMER_NOT_CREATED: "28",
  SOMETHING_WENT_WRONG: "96",
};
